### ISSUE TITLE
Commitment to keep this data forever

### ISSUE THREAD

**Issue by djalmaaraujo** [bluzi/jsonstore#18]
Hey, I think your project is amazing, but I am wondering who is paying the bill? If this get's expensive to you, how can we be safe about these servers not going down?

Can I suggest you create a donation/patreon button, etc? :)

oh, my I also suggest you the email of your users in case you need to explain why this project is shutting down in the future, etc.

Maybe a login with github would be enough.

**Comment by bluzi** [comment]
Hey, 

We've got some initial funds, but the plan is indeed to raise some funds from the community via donations in the near future. 

We're also planning on staying live for a while :) We have no intention to shutdown the service in the near future. I can't commit to forever, which sounds like a lot of time, but as much as I understand your concerns, we'll stay here.

**Comment by pedromassango** [comment]
yes, that is right. who is payng this?
our data is safe?
