### ISSUE TITLE
licensing

### ISSUE THREAD

**Issue by Niggler** [bluzi/jsonstore#2]
Thanks for making the service and releasing the source!

Just to be clear on the licensing, [`package.json`](https://github.com/bluzi/jsonstore/blob/master/package.json#L7) claims the license is ISC.  This is the default if you created the `package.json` file with `npm init`.  Was your intention to release as ISC or something else?  No matter what license you choose, please add an appropriate `LICENSE` file too

**Comment by bluzi** [comment]
Hey, 

Thanks, this is indeed a mistake, this project should be licensed under the MIT license. Would you mind making a pull request with this change?
