### ISSUE TITLE
Add GitHub topic “jsonstore”

### ISSUE THREAD

**Issue by peterhellberg** [bluzi/jsonstore#21]
There are currently two projects under https://github.com/topics/jsonstore
 
 - https://github.com/lmangani/gunstore.io
 - https://github.com/peterhellberg/jsonstore

We should add the `jsonstore` topic to this project as well.

**Comment by peterhellberg** [comment]
And now there is a third project under the `jsonstore` topic:

 - https://github.com/CzarSimon/jsonstore-go-client

**Comment by peterhellberg** [comment]
How about adding a clients section to the [README](https://github.com/bluzi/jsonstore/blob/master/README.md)?

**Comment by bluzi** [comment]
Awesome idea, I'll add the topic to the repository. 
Feel free to add the clients to the README and make a PR.
