### ISSUE TITLE
Restrictions per token

### ISSUE THREAD

**Issue by mcflurrybaby** [bluzi/jsonstore#22]
As it for now from the source code it seems, that there are no restrictions in size and amount of JSONs sent to this service. This is not safe at all. It will either force you to sell kidney in order to pay heroku/google bills, or service will stop working (if you limited quotas).
The easiest way, or 'first line' of defense may be restricting size/ amount of JSONs per endpoint. The other may be implementing OAuth via github and short live span of unregistered user's JSONs

**Comment by peterhellberg** [comment]
Having a quota per token won't work… since you can generate unlimited tokens

**Comment by mcflurrybaby** [comment]
Also it will work while authenticating via any service that requires phone confirmation. Everything is better than it is now:)

**Comment by peterhellberg** [comment]
On the other hand, being able to use this service without signing up is one of the main points of the project. (Otherwise you'd just sign up for some free data storage service)

**Comment by bluzi** [comment]
We do have some limitations in shape of Firebase triggers, just as defense against attacks.
I'm thinking about adding request rate limits, but I'm not sure about it since I want to keep the codebase "clean" so people can easily provision their own instances, and this feature will be useless for local instances.

Still thinking about it though.

**Comment by Gyvastis** [comment]
@peterhellberg what would those be?

**Comment by peterhellberg** [comment]
@Gyvastis There are numerous services with free plans. Some examples on top of my head: [Firebase](https://firebase.google.com/pricing/), [mLab](https://mlab.com/plans/pricing/#plan-type=sandbox), [ElephantSQL](https://www.elephantsql.com/plans.html), [Heroku Postgres](https://www.heroku.com/pricing#postgres-pricing)
