### ISSUE TITLE
bad Request....

### ISSUE THREAD

**Issue by Suleman-Elahi** [bluzi/jsonstore#27]
![image](https://user-images.githubusercontent.com/24384996/38851392-3192bb80-4233-11e8-8b7d-d797e3b5d833.png)

How to make it run on Windows 10 ?

**Comment by hackzilla** [comment]
The first issue is you need to turn off glob.

        -g, --globoff
              This  option  switches  off the "URL globbing parser". When you set this option,
              you can specify URLs that contain the letters {}[]  without  having  them  being
              interpreted  by  curl  itself.  Note that these letters are not normal legal URL
              contents but they should be encoded according to the URI standard.

Your second issue might be related to the first.
