### ISSUE TITLE
Support JSON Patch

### ISSUE THREAD

**Issue by n1k0** [bluzi/jsonstore#31]
http://jsonpatch.com/

The idea is to avoid retrieving the entire JSON content of a database to alter a single value and resubmit the entire modified content. So better perfs & concurrency.

**Comment by bluzi** [comment]
I like the overall idea, but unless I'm missing something here, I'm not sure it's providing something that we're not already providing. 

I mean, the equivalent of `{ "op": "replace", "path": "/baz", "value": "boo" }` in jsonstore would be sending a PUT request to `https://www.jsonstore.io/[token]/baz` and providing `"boo"` as a value, so you don't really have to retrieve the entire JSON.

LMK if I'm missing anything.

**Comment by n1k0** [comment]
I missed sub-paths were possible. I suppose this is now more a data-organization issue, which is not relevant to this project technically. Thanks!
