### ISSUE TITLE
[Question] Is there any quota or limitation on how much data i can store?

### ISSUE THREAD

**Issue by bauripalash** [bluzi/jsonstore#35]
I'm wondering if there's any limitations on data storage, such as how much data can i Store or how frequently i can send requests?

**Comment by bluzi** [comment]
There are no rate limits or storage limitations.
However, we do get alerts if something unusual happens, so if someone is trying to attack us we will know and we will block the attack. 

Also, jsonstore is meant to be used in small projects, so if you'll use it, let's say, as a logging solution for your enterprise B2C product, we will contact you and kindly ask you to stop.

Other than that, do what you want.

**Comment by bauripalash** [comment]
I'm thinking of implementing an open source , encrypted limited character messaging system, like the classic letter system.

**Comment by bluzi** [comment]
Go ahead

**Comment by bauripalash** [comment]
Thank You.
I'll soon send you the production link , after i complete my work.

**Comment by bauripalash** [comment]
@bluzi

I've reached the working alpha stage. Here's the repo link 

https://github.com/bauripalash/penme

And Here's the web app link, https://penme.ga

**Comment by bluzi** [comment]
Looking good, congrats!
