### ISSUE TITLE
Shipping in Development Mode

### ISSUE THREAD

**Issue by hmontazeri** [bluzi/jsonstore#4]
Any reason you shipping the frontend in dev mode? 

![image](https://user-images.githubusercontent.com/1557035/38381089-b59ed76a-38d3-11e8-9c04-13ccd056d882.png)

**Comment by peterhellberg** [comment]
This probably explains why it is _very_ slow to **POST** to www.jsonstore.io?

**Comment by hmontazeri** [comment]
@peterhellberg I don't think so, the frontend is served static (I hope). POST should be handled dynamic by Proxy / Node.

**Comment by darol100** [comment]
@hmontazeri That is what I call cutting edge.

**Comment by peterhellberg** [comment]
So should this issue be closed now?

**Comment by hmontazeri** [comment]
@peterhellberg it's not fixed so far...

**Comment by bluzi** [comment]
fixed
