### ISSUE TITLE
Suggestion: Endpoint Protection

### ISSUE THREAD

**Issue by melwinalm** [bluzi/jsonstore#47]
JSONStore is an amazing tool to store JSON data, which can be used to consume data from endpoints. The random URL is going to provide a certain level of data security. But if you could add additional security to this using something like - password protection for POST, PUT and DELETE requests. 

Imagine, I am using JSONStore to store some data which will be consumed in my app. The app is only going to make GET requests only. But I being the owner of the app and the endpoint, can go ahead and make updates to the JSONStore endpoint. This way some third party can consume the endpoint data, but cannot make any changes to it.

This is just a suggestion that triggered in me. I am thinking of using JSONStore for one of my android apps. But since it does not provide endpoint protection, I am a bit skeptical about using this service.

Amazing work, by the way.

**Comment by vikkio88** [comment]
you just need to proxy through the endpoint and use this service as a db
