### ISSUE TITLE
It's DOWN?!

### ISSUE THREAD

**Issue by jajoosam** [bluzi/jsonstore#52]
With any new DB I create, fetching data always returns
```
{
"ok": false
}
```

Can you please get on this ASAP?
Many of my projects rely on jsonstore

**Comment by bluzi** [comment]
Yes, we were under attack yesterday and we're facing some issues. I'll keep you posted.

**Comment by jajoosam** [comment]
Is data preserved? And, is there anything I can do to help?

**Comment by bluzi** [comment]
Yes, data is preserved.
Unfortunately no, there's nothing you can do at the moment
