### ISSUE TITLE
Down?

### ISSUE THREAD

**Issue by brianmueller** [bluzi/jsonstore#57]
Is jsonstore down? I've been using it for a while but nothing is working right now. When I do a `curl -XGET` in my terminal, I see
```
<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>
```

**Comment by spencerpogo** [comment]
Same issue here. Visiting in the browser gives me the following: 
![image](https://user-images.githubusercontent.com/34356756/63733022-a9d57b80-c82b-11e9-96d5-d109b7235665.png)

Love this service but hope this gets fixed.

**Comment by ghost** [comment]
I'm not having any issues with right now with JSONstore:
![image](https://user-images.githubusercontent.com/22669894/63734604-43e70380-c8c0-11e9-8442-8726f5f3bb09.png)

Does clearing your cache & cookies help?

**Comment by bluzi** [comment]
Hey everyone, I can confirm that we've been attacked and the service is down.
The website is still working but the API does not respond. 

Don't worry about your data, the service will be back soon.

**Comment by whateverworksforme** [comment]
Is it still down? My app was down for many hours. Moving to https://jsonbin.io for stability until the service is back up and functional.

**Comment by spencerpogo** [comment]
Sorry to hear that. Thanks for the update.

**Comment by jajoosam** [comment]
@bluzi any ETA for the fix?

**Comment by bluzi** [comment]
Jsonstore is back, sorry for the inconvenience. Have fun!

**Comment by whateverworksforme** [comment]
Thanks for the update

**Comment by brianmueller** [comment]
Thank you!!
