### ISSUE TITLE
JSONstore.io dead?

### ISSUE THREAD

**Issue by downitch** [bluzi/jsonstore#62]
seems like there is an issue with service as it redirects to heroku's application error asking to check logs. Before redirecting there it's been a while with response of status 500 and JSON response:
```
{ "ok": false }
```

**Comment by neelr** [comment]
Same here, I try to post and I get a heroku error

**Comment by DavidErkul** [comment]
few hours ago got 500 errors and now heroku error...

**Comment by brianmueller** [comment]
Same issue here. Any updates?

**Comment by ghost** [comment]
Ok, time to switch on MongoDB...

**Comment by bluzi** [comment]
We're having technical issues that will be resolved in the next few days.

**Comment by PixelNinja132** [comment]
> We're having technical issues that will be resolved in the next few days.

any news?

**Comment by brianmueller** [comment]
The tiny app I prototyped with jsonstore seems to be working just fine. Hopefully others are having luck, too! Either that, or I’m speaking too soon.

**Comment by downitch** [comment]
Looks like jsonstore works! :)

**Comment by Skyinto** [comment]
Rip JSONSTORE.IO

**Comment by PixelNinja132** [comment]
> Rip JSONSTORE.IO

Ur like 3 months late mate
