### ISSUE TITLE
Heroku Error on all Requests (GET, POST, etc)

### ISSUE THREAD

**Issue by jvanord** [bluzi/jsonstore#63]
Heroku is returning error responses for all stored JSON documents for all request verbs. This occurs for new and longer-saved documents.
The screenshot below is the result of any GET request through a browser.
![image](https://user-images.githubusercontent.com/17397251/67254134-62452780-f449-11e9-8e38-178e5a431057.png)

**Comment by neelr** [comment]
Yeah, same issue as https://github.com/bluzi/jsonstore/issues/62

**Comment by bluzi** [comment]
We're having technical issues that will be resolved in the next few days.
