### ISSUE TITLE
DELETE returns HTTP/1.1 500 Internal Server Error

### ISSUE THREAD

**Issue by scorphus** [bluzi/jsonstore#8]
I'm getting HTTP/1.1 500 Internal Server Error while trying to delete a resource

**Comment by bluzi** [comment]
Thank you @scorphus, we are aware of that and working on a fix.

**Comment by scorphus** [comment]
I'm reading the Firebase JS reference to see if I can help and come up with a PR. Should I abort?

**Comment by bluzi** [comment]
Go for it

**Comment by scorphus** [comment]
Cool!
